name: venturo_java_code
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  app_settings: ^4.1.8
  badges: ^2.0.3
  cached_network_image: ^3.2.2
  connectivity_plus: ^3.0.2
  cupertino_icons: ^1.0.2
  device_info_plus: ^8.0.0
  device_preview: ^1.1.0
  dio: ^4.0.6
  equatable: ^2.0.5
  firebase_core: ^2.3.0
  firebase_crashlytics: ^3.0.6
  firebase_messaging: ^14.1.1
  flutter:
    sdk: flutter
  flutter_conditional_rendering: ^2.0.0
  flutter_html: ^3.0.0-alpha.3
  flutter_launcher_icons: ^0.11.0
  flutter_local_notifications: ^9.6.1
  flutter_screenutil: ^5.6.0
  flutter_svg: ^1.1.6
  freezed_annotation: ^2.2.0
  geocoding: ^2.0.5
  geolocator: ^9.0.2
  get: ^4.6.5
  google_fonts: ^3.0.1
  google_sign_in: ^5.4.2
  image_cropper: ^3.0.1
  image_picker: ^0.8.6
  intl: ^0.17.0
  json_annotation: ^4.7.0
  local_auth: ^2.1.2
  path_provider: ^2.0.11
  pinput: ^2.2.16
  screenshot: ^1.2.3
  share_plus: ^6.3.0
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  uni_links: ^0.5.1

dev_dependencies:
  build_runner: ^2.3.2

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.2.1
  json_serializable: ^6.5.4

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  assets:
    - assets/images/
    #    - assets/lottie/
    - assets/svg/
